# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.7.1.1.9999
#hackport: flags: -build-readme

CABAL_FEATURES="lib profile haddock hoogle hscolour"
CABAL_HACKAGE_REVISION=1

inherit haskell-cabal

DESCRIPTION="Utility package for constraints"
HOMEPAGE="https://github.com/obsidiansystems/constraints-extras"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/constraints-0.9:=[profile?] <dev-haskell/constraints-0.14:=[profile?]
	>=dev-lang/ghc-8.4.3:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2.0.1
"

CABAL_CHDEPS=(
	'base >=4.9 && <4.18' 'base >=4.9 && <4.19'
	'template-haskell >=2.11 && <2.20' 'template-haskell >=2.11 && <2.21'
)

src_configure() {
	haskell-cabal_src_configure \
		--flag=-build-readme
}
