# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A library for algebraic graph construction and transformation"
HOMEPAGE="https://github.com/snowleopard/alga"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/extra-1.4 <dev-haskell/extra-2
		>=dev-haskell/inspection-testing-0.4.2.2
		>=dev-haskell/quickcheck-2.14 <dev-haskell/quickcheck-2.16 )
"
