# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_HACKAGE_REVISION=6

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Convenient interface for printing colourful messages"
HOMEPAGE="https://github.com/kowainik/colourista"

LICENSE="MPL-2.0"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND="
<<<<<<< HEAD:dev-haskell/colourista/colourista-0.1.0.2-r1.ebuild
	>=dev-haskell/ansi-terminal-0.10:=[profile?] <dev-haskell/ansi-terminal-1.1:=[profile?]
	>=dev-haskell/text-1.2.3.0:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-lang/ghc-8.10.6:=
=======
	>=dev-haskell/ansi-terminal-0.10:=[profile?] <dev-haskell/ansi-terminal-1.2:=[profile?]
	>=dev-haskell/text-1.2.3.0:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-lang/ghc-9.0.2:=
>>>>>>> 268e96b80306321546b8e491870c64710eab7ff2:dev-haskell/colourista/colourista-0.1.0.2-r2.ebuild
"
DEPEND="
	${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? (
		>=dev-haskell/hspec-2.7.1 <dev-haskell/hspec-2.12
	)
"
