# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Library for parsing GHC time and allocation profiling reports"
HOMEPAGE="https://github.com/maoe/ghc-prof"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="dump"

CABAL_CHDEPS=(
	'base >= 4.6 && < 4.20' 'base >= 4.6'
	'containers >= 0.5 && < 0.7' 'containers >= 0.5'
	'tasty < 1.5' 'tasty'
)

RDEPEND="<dev-haskell/attoparsec-0.15:=[profile?]
	<dev-haskell/scientific-0.4:=[profile?]
	<dev-haskell/text-2.2:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/attoparsec-0.10
		dev-haskell/tasty
		>=dev-haskell/tasty-hunit-0.9.1 <dev-haskell/tasty-hunit-0.11
		dev-haskell/temporary )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag dump dump)
}
