# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.2.1.9999

CABAL_HACKAGE_REVISION=1
CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Extend Cabal build-depends from the command line"
HOMEPAGE="https://haskell-ci.rtfd.org/"

LICENSE="GPL-2 BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND="
	>=dev-haskell/base16-bytestring-1.0.0.0:=[profile?] <dev-haskell/base16-bytestring-1.1:=[profile?]
	>=dev-haskell/cabal-3.6:=[profile?] <dev-haskell/cabal-3.15:=[profile?]
	>=dev-haskell/cabal-install-parsers-0.4.1:=[profile?] <dev-haskell/cabal-install-parsers-0.7:=[profile?]
	>=dev-haskell/cabal-syntax-3.10.1.0:=[profile?] <dev-haskell/cabal-syntax-3.15:=[profile?]
	>=dev-haskell/optparse-applicative-0.16:=[profile?] <dev-haskell/optparse-applicative-0.19:=[profile?]
	>=dev-lang/ghc-8.8.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.0.0.0
	test? (
		>=dev-haskell/ansi-terminal-0.10 <dev-haskell/ansi-terminal-0.12
		>=dev-haskell/tasty-1.4 <dev-haskell/tasty-1.5
		>=dev-haskell/tasty-golden-2.3.1.1 <dev-haskell/tasty-golden-2.4
		>=dev-haskell/tasty-hunit-0.10.0.2 <dev-haskell/tasty-hunit-0.11
		>=dev-haskell/tree-diff-0.2 <dev-haskell/tree-diff-0.4
	)
"
